---

- hosts: all
  become: true


  tasks:

  - name: Autoremove unused packages to save some disk space
    command: apt-get -y autoremove
    #apt: autoremove=yes in Ansible 2.1+

  - name: Install unzip for unpacking files later on
    apt: pkg=unzip state=latest

  - name: Install NTP to avoid time drift inside the VM
    apt: name=ntp state=latest


  - name: Add a repository for JDK8 on Ubuntu 14.04
    apt_repository: repo='ppa:openjdk-r/ppa'
    when: "ansible_distribution == 'Ubuntu' and ansible_lsb.major_release|int <= 14"

  - name: Install the JRE
    apt: pkg=openjdk-8-jre-headless state=latest update_cache=yes install_recommends=no


  - name: Get Elasticsearch
    get_url:
      url=https://download.elasticsearch.org/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/5.0.0-alpha2/elasticsearch-5.0.0-alpha2.deb
      dest=/opt/elasticsearch.deb

  - name: Install Elasticsearch
    apt: deb=/opt/elasticsearch.deb

  - name: Make sure Elasticsearch autostarts and is started now
    service: name=elasticsearch enabled=yes state=started


  - name: Get Logstash
    get_url:
      url=https://download.elastic.co/logstash/logstash/packages/debian/logstash-5.0.0-alpha2_all.deb
      dest=/opt/logstash.deb

  - name: Install Logstash
    apt: deb=/opt/logstash.deb

  - name: Make sure Logstash autostarts and is started now
    service: name=logstash enabled=yes state=started


  - name: Get Filebeat
    get_url:
      url=https://download.elastic.co/beats/filebeat/filebeat_5.0.0-alpha2_amd64.deb
      dest=/opt/filebeat.deb

  - name: Install Filebeat
    apt: deb=/opt/filebeat.deb

  - name: Get Topbeat
    get_url:
      url=https://download.elastic.co/beats/topbeat/topbeat_5.0.0-alpha2_amd64.deb
      dest=/opt/topbeat.deb

  - name: Install Topbeat
    apt: deb=/opt/topbeat.deb

  - name: Get Packetbeat
    get_url:
      url=https://download.elastic.co/beats/packetbeat/packetbeat_5.0.0-alpha2_amd64.deb
      dest=/opt/packetbeat.deb

  - name: Install Packetbeat
    apt: deb=/opt/packetbeat.deb

  - name: Make sure Filebeat, Topbeat, and Packetbeat autostart and are started now
    service: name={{ item }} enabled=yes state=started
    with_items:
      - filebeat
      - topbeat
      - packetbeat

  - name: Download Timelion
    get_url:
      url=https://download.elastic.co/kibana/timelion/timelion-5.0.0-alpha2.zip
      dest=/opt/timelion.zip


  - name: Get Kibana
    get_url:
      url=https://download.elastic.co/kibana/kibana/kibana_5.0.0-alpha2_amd64.deb
      dest=/opt/kibana.deb

  - name: Install Kibana
    apt: deb=/opt/kibana.deb

  - name: Make sure Kibana autostarts and is started now
    service: name=kibana enabled=yes state=started


  - name: Install nginx
    apt: pkg=nginx state=latest

  - name: Install Python Passlib so the nginx credentials can be hashed
    apt: name=python-passlib state=latest update_cache=yes


  - name: Make the all.sh script executable
    file: path=/elastic-stack/all.sh mode=0755
