---

- hosts: all
  become: true


  vars:
    elastic_version: 5.0.0-alpha3


  tasks:

  - name: Get rid of Chef and Puppet to save some resources and autoremove unused packages to save some disk space
    apt: name={{ item }} state=absent autoremove=yes
    with_items:
      - chef
      - puppet

  - name: Install unzip for unpacking files later on
    apt: name=unzip state=latest

  - name: Install NTP to avoid time drift inside the VM
    apt: name=ntp state=latest


  - name: Add the repository for JDK8 on Ubuntu 14.04
    apt_repository: repo='ppa:openjdk-r/ppa'
    when: "ansible_distribution == 'Ubuntu' and ansible_lsb.major_release|int <= 14"

  - name: Install the JRE
    apt: name=openjdk-8-jre-headless state=latest update_cache=yes install_recommends=no


  - name: Get Elasticsearch
    get_url:
      url=https://download.elasticsearch.org/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/{{ elastic_version }}/elasticsearch-{{ elastic_version }}.deb
      dest=/opt/elasticsearch.deb

  - name: Install Elasticsearch
    apt: deb=/opt/elasticsearch.deb

  - name: Make sure Elasticsearch autostarts and is started now
    service: name=elasticsearch enabled=yes state=started


  - name: Get Logstash
    get_url:
      url=https://download.elastic.co/logstash/logstash/packages/debian/logstash-{{ elastic_version }}.deb
      dest=/opt/logstash.deb

  - name: Install Logstash
    apt: deb=/opt/logstash.deb

  - name: Make sure Logstash autostarts and is started now
    service: name=logstash enabled=yes state=started


  - name: Get Filebeat
    get_url:
      url=https://download.elastic.co/beats/filebeat/filebeat-{{ elastic_version }}-amd64.deb
      dest=/opt/filebeat.deb

  - name: Install Filebeat
    apt: deb=/opt/filebeat.deb

  - name: Get Metricbeat
    get_url:
      url=https://download.elastic.co/beats/metricbeat/metricbeat-{{ elastic_version }}-amd64.deb
      dest=/opt/metricbeat.deb

  - name: Install Metricbeat
    apt: deb=/opt/metricbeat.deb

  - name: Get Packetbeat
    get_url:
      url=https://download.elastic.co/beats/packetbeat/packetbeat-{{ elastic_version }}-amd64.deb
      dest=/opt/packetbeat.deb

  - name: Install Packetbeat
    apt: deb=/opt/packetbeat.deb

  - name: Make sure Filebeat, Mtricbeat, and Packetbeat autostart and are started now
    service: name={{ item }} enabled=yes state=started
    with_items:
      - filebeat
      - metricbeat
      - packetbeat


  - name: Get Kibana
    get_url:
      url=https://download.elastic.co/kibana/kibana/kibana_{{ elastic_version }}_amd64.deb
      dest=/opt/kibana.deb

  - name: Install Kibana
    apt: deb=/opt/kibana.deb

  - name: Make sure Kibana autostarts and is started now
    service: name=kibana enabled=yes state=started

  - name: Download Timelion
    get_url:
      url=https://download.elastic.co/kibana/timelion/timelion-{{ elastic_version }}.zip
      dest=/opt/timelion.zip


  - name: Install nginx so we can use it as a reverse proxy
    apt: pkg=nginx state=latest

  - name: Install Python Passlib so the nginx credentials can be hashed
    apt: name=python-passlib state=latest update_cache=yes


  - name: Make the all.sh script executable
    file: path=/elastic-stack/all.sh mode=0755


  - name: Get the injector plugin to generate test data
    get_url:
      url=https://download.elastic.co/workshops/basic-kibana/injector/injector-5.0.jar
      dest=/elastic-stack/injector-5.0.jar
      mode=0755
