---

- hosts: localhost
  become: true


  tasks:

  - name: Change Elasticsearch's memory usage to 512MB
    lineinfile: dest=/etc/elasticsearch/jvm.options regexp="^-Xms" line="-Xms512m" state=present
  - lineinfile: dest=/etc/elasticsearch/jvm.options regexp="^-Xmx" line="-Xmx512m" state=present

  - name: Start Elasticsearch
    service: name=elasticsearch state=started
