---

- hosts: localhost
  become: true


  tasks:

  - name: Make Kibana only available on localhost since we'll proxy it through nginx
    lineinfile: "dest=/etc/kibana/kibana.yml regexp=^server.host line='server.host: \"localhost\"'"

  - name: Restart Kibana to apply the configuration change
    service: name=kibana state=restarted

  - name: Set up the nginx credentials
    htpasswd: path=/etc/nginx/htpasswd.users name=admin password=admin

  - name: Add a customized nginx configuration
    template: src=templates/nginx dest=/etc/nginx/sites-available/default

  - name: Start Kibana
    service: name=kibana state=started
