---

- hosts: localhost
  become: true


  tasks:

  - name: Make Kibana available on all network interfaces
    lineinfile: "dest=/etc/kibana/kibana.yml regexp='^# server.host' line='server.host: \"0.0.0.0\"' state=present"

  - name: Start Kibana
    service: name=kibana state=started
