---

- hosts: localhost
  become: true


  tasks:

  - name: Change the Metricbeat configuration
    template: src=templates/metricbeat.yml dest=/etc/metricbeat/metricbeat.yml

  - name: Start Metricbeat
    service: name=metricbeat state=restarted
