---

- hosts: localhost
  become: true


  tasks:

  - name: Change the Packetbeat configuration
    template: src=templates/packetbeat.yml dest=/etc/packetbeat/packetbeat.yml

  - name: Restart Packetbeat
    service: name=packetbeat state=restarted

  - name: Wait if Packetbeat is actually running
    pause: seconds=3

  - name: Get the state of all services and check the status of Packetbeat
    service_facts: ~
    failed_when: ansible_facts.services.packetbeat.state != "running"

  - name: Check if we actually have documents in Packetbeat's index
    uri:
      url: http://localhost:9200/packetbeat-*/_count
      method: GET
      status_code:
        - 200
      return_content: yes
    register: response
    failed_when: 'response.json["count"]|int == 0'
