---

- hosts: localhost
  become: true


  tasks:

  - name: Change the Metricbeat configuration
    template: src=templates/metricbeat.yml dest=/etc/metricbeat/metricbeat.yml

  - name: Restart Metricbeat
    service: name=metricbeat state=restarted

  - name: Wait if Metricbeat is actually running
    pause: minutes=2

  - name: Get the state of all services and check the status of Metricbeat
    service_facts: ~
    failed_when: ansible_facts.services.metricbeat.state != "running"

  - name: Check if we actually have documents in Metricbeat's index
    uri:
      url: http://localhost:9200/metricbeat-*/_count
      method: GET
      status_code:
        - 200
      return_content: yes
    register: response
    failed_when: 'response.json["count"]|int == 0'
