---

- hosts: localhost
  become: true


  tasks:

  - name: Change the Auditbeat configuration
    template: src=templates/auditbeat.yml dest=/etc/auditbeat/auditbeat.yml

  - name: Restart Auditbeat
    service: name=auditbeat state=restarted

  - name: Wait if Auditbeat is actually running
    pause: seconds=3

  - name: Get the state of all services and check the status of Auditbeat
    service_facts: ~
    failed_when: ansible_facts.services.auditbeat.state != "running"
