---

- hosts: localhost
  become: true


  tasks:

  - name: Change the Packetbeat configuration
    template: src=templates/packetbeat.yml dest=/etc/packetbeat/packetbeat.yml
    vars:
      output: elasticsearch

  - name: Restart Packetbeat
    service: name=packetbeat state=restarted

  - name: Once index template and dashboards have been applied, switch to Redis
    template: src=templates/packetbeat.yml dest=/etc/packetbeat/packetbeat.yml
    vars:
      output: redis

  - name: Restart Packetbeat
    service: name=packetbeat state=restarted

  - name: Wait if Packetbeat is actually running
    pause: seconds=3

  - name: Get the state of all services and check the status of Packetbeat
    service_facts: ~
    failed_when: ansible_facts.services.packetbeat.state != "running"
