filebeat.prospectors:

- input_type: log
  paths:
    - /var/log/syslog
  document_type: syslog

- input_type: log
  paths:
    - /var/log/kibana/kibana.log
  document_type: kibana
  json.message_key: log


output.logstash:
  hosts: ["localhost:5044"]
