metricbeat.modules:


- module: system
  metricsets:
    - cpu
    - load
    #- core
    #- diskio
    - filesystem
    #- fsstat
    - memory
    - network
    - process
  enabled: true
  period: 10s
  processes: ['.*']


output.logstash:
  hosts: ["localhost:9200"]
